Build fix for MSVC 2019
Fixes failures like:
..\..\src\plugins\help\qlitehtml\litehtml\src\num_cvt.cpp(62):
error C2440: 'initializing': cannot convert from 'const char [2]' to
'litehtml::tchar_t *' ..\..\src\plugins\help\qlitehtml\litehtml\src\num_cvt.cpp(62):
note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)